app_key: <%= ENV['DBX_APP_KEY'] %>
app_secret: <%= ENV['DBX_APP_SECRET'] %>
access_token: <%= ENV['DBX_ACCESS_TOKEN'] %>
access_token_secret: <%= ENV['DBX_ACCESS_TOKEN_SECRET'] %>
user_id: <%= ENV['DBX_USER_ID'] %>
access_type: <%= ENV['DBX_ACCESS_TYPE'] %>
